version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      VITE_NEWS_DATA_KEY: pub_331439d249ac55ced2eee35ca30687af9255b
    volumes:
      - .:/home/node/app
